image: node:22-alpine

stages:
  - deploy

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - cp dist/index.html dist/404.html
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
